Traceback (most recent call last):
  File "02_acquire_app_info.py", line 76, in validate_parsed_data
AssertionError: appid does not match queried appid
