Traceback (most recent call last):
  File "02_acquire_app_info.py", line 53, in validate_text_data
    data = parse_responses(appid, app_details, app_reviews)
  File "02_acquire_app_info.py", line 33, in parse_responses
    app_reviews = json.loads(app_reviews)
  File "C:\Users\novel\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\novel\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\novel\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
